add_ox_quiz(1, "Coca-cola was originally sold as a medicine.", true)
add_ox_quiz(1, "Wind Resistance cannot be a bonus in a helm.", false)
add_ox_quiz(1, "The Hundred Years War lasted for 136 years.", false)
add_ox_quiz(1, "Polar bears need cold temperatures and a lot of ice in order to hunt for food.", false)
add_ox_quiz(1, "The McDonalds fast food chain was founded by a clown called Ronald.", false)
add_ox_quiz(1, "The PandemoniA guild has a Weapon Blacksmith.", false)
add_ox_quiz(1, "Michael Jackson, Queen and Raphael are 3 artists who achieved a Uranium Disc Award.", false)
add_ox_quiz(1, "Bats are mammals that fly. They are endothermic. They have fur instead of feathers and nurse their young.", true)
add_ox_quiz(1, "The PandemoniA guild has an Accessories Blacksmith.", true)
add_ox_quiz(1, "Predators such as coyotes, foxes, and owls find the snowshoe rabbit easy prey.", true)
add_ox_quiz(1, "There is no speed limit in the British highways.", false)
add_ox_quiz(1, "The house mouse came to America on ships with the first explorers and are originally from central Asia.", true)
add_ox_quiz(1, "`Alice in Wonderland` was written by Lewis Carroll.", true)
add_ox_quiz(1, "As with all rodents, the rabbit must keep gnawing or his teeth will grow so long it will not be able to use them.", true)
add_ox_quiz(1, "CPU stands for Central Processing Unitext.", false)
add_ox_quiz(1, "Weasels are generally very lazy and this explains why they do not flee in spite of being capable.", true)
add_ox_quiz(1, "The Infernal guild has an Accessories Blacksmith.", true)
add_ox_quiz(1, "Dolphins and porpoises are fish", false)
add_ox_quiz(1, "Yang was the old currency in Korea.", true)
add_ox_quiz(1, "It is common practice to measure the height of a horse by hands.", true)
add_ox_quiz(1, "Catholic Church popes were allowed to get married.", false)
add_ox_quiz(1, "All trees have leaves.", false)
add_ox_quiz(1, "The Alive guild has an Armor Blacksmith.", false)
add_ox_quiz(1, "Human immunodeficiency virus (HIV) is a lentivirus", true)
add_ox_quiz(1, "The Resurrection guild has an accessories blacksmith.", false)
add_ox_quiz(1, "Oncology is a branch of medicine that deals with tumors (cancer).", true)
add_ox_quiz(1, "The ThreeLands guild has a weapon blacksmith.", true)
add_ox_quiz(1, "Samurai is the term for the military nobility of pre-industrial Japan.", true)
add_ox_quiz(1, "The Elite Vile Demon King can drop Treasure Chests.", true)
add_ox_quiz(1, "Dragon Ball is a Japanese manga series written and illustrated by Akira Toriyama.", true)
add_ox_quiz(1, "Unknown Medicine is dropped by Plagued Men.", false)
add_ox_quiz(1, "Naruto is a Japanese manga series written and illustrated by Akira Kurosawa.", false)
add_ox_quiz(1, "Bear foot is needed to upgrade a wood bracelet to +9.", false)
add_ox_quiz(1, "Bleach is a chemical that improves colors or whitens, often via oxidation.", false)
add_ox_quiz(1, "2 orc tooth+ and clam are needed to upgrade a jade necklace to +9.", true)
add_ox_quiz(1, "Bleach is a chemical that removes colors or whitens, often via oxidation.", true)
add_ox_quiz(1, "2 ornamental hairpins and a clam are needed to upgrade jade necklace to +9.", false)
add_ox_quiz(1, "The Liger is a cross between a male lion and a tigress.", true)
add_ox_quiz(1, "Broken china is needed to upgrade a long sword to +9.", true)
add_ox_quiz(1, "Demon’s Fan +6 has plus 20% attack speed.", false)
add_ox_quiz(1, "Bear foot is needed to upgrade a long sword to +9.", false)
add_ox_quiz(1, "Demon’s Fan +7 has 15% against demi-human,", false)
add_ox_quiz(1, "2 snakeskins and clams are needed to upgrade silver sword to +9.", true)
add_ox_quiz(1, "Edge Blade +8 has 8% against demi-human.", false)
add_ox_quiz(1, "Scotland Yard is the name of a branch of the London police force", true)
add_ox_quiz(1, "The shock of an electric eel can knock a man down.", true)
add_ox_quiz(1, "To upgrade a Pickaxe to +8 you need a Pickaxe+7 with 76800 points.", false)
add_ox_quiz(1, "To upgrade a Fishing Pole to +9 you need a Fishing Pole +8 with 220 points.", false)
add_ox_quiz(1, "Tiger earrings increase defense by 300.", false)
add_ox_quiz(1, "You can wear Wedding Dress if you are a lvl 35 female warrior.", true)
add_ox_quiz(1, "You can wear Black Tunic+8 if you are a lvl 69 female archer.", false)
add_ox_quiz(1, "To upgrade a Fishing Pole to +20 you need a Fishing Pole +19 with 420 points.", true)
add_ox_quiz(1, "You can wear Black Tunic+8 if you are a lvl 68 female mage.", false)
add_ox_quiz(1, "You need ice marble x2 and red pearl to upgrade Black Tunic from +8 to +9.", true)
add_ox_quiz(1, "Copper Bracelet+ increases max hp by 180.", false)
add_ox_quiz(1, "If you use Blessing spell and you fail to upgrade, your item will be degraded by 1.", false)
add_ox_quiz(1, "King Spider is lvl 65.", true)
add_ox_quiz(1, "Grilled Rainbow Trout restores 800 sp.", false)
add_ox_quiz(1, "Grilled Tilapia restores 250 sp.", false)
add_ox_quiz(1, "Grilled Tenchi restores 250 hp.", false)
add_ox_quiz(1, "Grilled Lotus Fish restores 500 hp.", true)
add_ox_quiz(1, "To upgrade a Pickaxe to +9 you need a Pickaxe+8 with 1536000 points.", true)
add_ox_quiz(1, "To upgrade a Pickaxe to +2 you need a Pickaxe+1 with 120000 points.", false)
add_ox_quiz(1, "Neanderthal's brains were bigger than ours (Homo Sapiens).", true)
add_ox_quiz(1, "The exact middle of the year is June 28th.", false)
add_ox_quiz(1, "More than 1.5 million people die each year from malaria.", true)
add_ox_quiz(1, "A 'jiffy' is an actual unit of time.", true)
add_ox_quiz(1, "The collective noun for a group of barracuda is `battery`.", true)
add_ox_quiz(1, "A snail can sleep for 3 years.", true)
add_ox_quiz(1, "Grilled Grayling restores 350 sp.", false)
add_ox_quiz(1, "Grilled Carp increases spell speed by 20 for 10 mins.", false)
add_ox_quiz(1, "It is impossible to get a McDonald's Happy Meal in New Delhi, India.", false)
add_ox_quiz(1, "Neil Armstrong said: 'That's one small step for man, one giant leap for mankind'.", true)
add_ox_quiz(1, "The average human body contains enough sulphur to fire a toy cannon.", false)
add_ox_quiz(1, "In the arcade game 'Ms Pac-Man', the ghosts are named Inky, Blinky, Pinky and Sue.", true)
add_ox_quiz(1, "Self-hypnosis is a cure for stuttering.", false)
add_ox_quiz(1, "Skunks eat bees.", true)
add_ox_quiz(1, "Over 90 percent of the student body at Alabama State University are African American.", true)
add_ox_quiz(1, "The United Nations was originally headquartered in San Francisco.", false)
add_ox_quiz(1, "The language with the most native speakers in the world is Chinese.", true)
add_ox_quiz(1, "Drinking coffee cannot help you sober up.", true)
add_ox_quiz(1, "Saturn is the third largest planet after Jupiter and Neptune.", false)
add_ox_quiz(1, "The primary colors are red, yellow, and blue.", false)
add_ox_quiz(1, "True Roquefort cheese is made from ewe's milk.", true)
add_ox_quiz(1, "The dog, Rin Tin Tin was actually a female dog.", false)
add_ox_quiz(1, "Peter Finch was the first actor to be nominated for an Oscar posthumously.", false)
add_ox_quiz(1, "English scientists have found the soya, sage and ginseng may hold the key to boosting memory.", true)
add_ox_quiz(1, "Elton John's real name was Reginald Dwight.", true)
add_ox_quiz(1, "Former governor Jesse Ventura appeared in the 1997 movie, 'Batman and Robin'.", true)
add_ox_quiz(1, "King Kong was found on Marsh Island.", false)
add_ox_quiz(1, "Niagara Falls is the highest waterfall in the world.", false)
add_ox_quiz(1, "Gaul was the ancient name of France.", true)
add_ox_quiz(1, "Walt Disney had a job on a railroad.", true)
add_ox_quiz(1, "A human has more DNA material than a green pea.", false)
add_ox_quiz(1, "'The William Tell Overture' was the theme song for 'The Lone Ranger'.", true)
add_ox_quiz(1, "Coca-Cola used to contain cocaine.", true)
add_ox_quiz(1, "Amerigo Vespucci was the first European to suggest that the Americas were not the East Indies.", true)
add_ox_quiz(1, "In the Lord of the Rings, Saruman lives in Cirith Ungol.", false)
add_ox_quiz(1, "The capital of Morocco is Sahara.", false)
add_ox_quiz(1, "The capital of Jamaica is Port Antonio.", false)
add_ox_quiz(1, "The actor who has raised the most money in films throughout his career is Samuel L. Jackson.", true)
add_ox_quiz(1, "At $7 million, the music video, 'Scream' featuring Janet Jackson, is by far the most expensive clip ever produced.", false)
add_ox_quiz(1, "Paris Hilton's dog is called Tinkerbell.", true)
add_ox_quiz(1, "Tiger hide is needed to upgrade an iron fan to +7.", true)
add_ox_quiz(1, "A necklace at lvl 42+7 gives 4 Strength.", false)
add_ox_quiz(1, "A Moderator can teleport himself anywhere and become invisible.", false)
add_ox_quiz(1, "India and Sri Lanka were linked by land until the 15th century.", true)
add_ox_quiz(1, "You can win Mileage Points in the Guild Tournament.", true)
add_ox_quiz(1, "You need a String in Peddler’s quest mission.", true)
add_ox_quiz(1, "The Swedish flag has two different colors.", true)
add_ox_quiz(1, "The Greek region of Mount Athos is forbidden to men.", false)
add_ox_quiz(1, "The 5th place of the first Ultimate Guild Tournament was awarded to the Exile guild.", false)
add_ox_quiz(1, "The south Korean monetary currency is called Won.", true)
add_ox_quiz(1, "All plants are safe to eat.", false)
add_ox_quiz(1, "Many insects do not die through the winter in cold climates.", true)
add_ox_quiz(1, "Moby Dick was filmed by Herman Melville.", false)
add_ox_quiz(1, "The world's tallest building is located in the USA.", false)
add_ox_quiz(1, "Metin 2 servers run on the BSD operating system.", true)
add_ox_quiz(1, "The country also known as 'Copper Land' is Zambia.", true)
add_ox_quiz(1, "The last letter of the Greek alphabet is Omega.", true)
add_ox_quiz(1, "The last stand of the Eastern Roman Empire was in 1551.", false)
add_ox_quiz(1, "2 Ornamental Hairpin are needed to upgrade a Cobra Dagger +7.", false)
add_ox_quiz(1, "Red Packets may contain Blacksmith Memos.", true)
add_ox_quiz(1, "Elephants are the largest mammals on Earth.", false)
add_ox_quiz(1, "Tree roots are useless and just sit in the ground doing nothing.", false)
add_ox_quiz(1, "Classical music originated in the USA in the late eighties.", false)
add_ox_quiz(1, "Quentin Tarantino directed Reservoir Dogs.", true)
add_ox_quiz(1, "Northern Ireland is the smallest country to ever qualify for Soccer World Cup.", false)
add_ox_quiz(1, "Carolina Herrera is not a real person. It's just a brand name.", false)
add_ox_quiz(1, "The Infernal guild has an Armor Blacksmith.", false)
add_ox_quiz(1, "2 bear gall is needed to upgrade a silver bell to +7.", false)
add_ox_quiz(1, "Lewis Hamilton is the highest paid sportsman in the world.", false)
add_ox_quiz(1, "Joan is located in Elgoria.", false)
add_ox_quiz(1, "Stephen King's novel Shining takes place in a Hotel.", true)
add_ox_quiz(1, "Frédéric François Chopin was a Polish music teacher.", true)
add_ox_quiz(1, "Sierra Leone's capital is Victoria.", false)
add_ox_quiz(1, "The capital of Paraguay is Ascension.", false)
add_ox_quiz(1, "Elvis Presley never had a karate black-belt.", false)
add_ox_quiz(1, "FBI means Federal Bureau of Investigation.", true)
add_ox_quiz(1, "Cream is heavier than milk.", false)
add_ox_quiz(1, "A luthier is a violin maker.", true)
add_ox_quiz(1, "The chemical symbol for Potassium is P.", false)
add_ox_quiz(1, "No United States President has ever been elected unanimously.", false)
add_ox_quiz(1, "In the Stephen King novel 'IT', the Clown Pennywise turns out to be human.", false)
add_ox_quiz(1, "If you have an I.Q. above 140 you are considered a genius.", true)
add_ox_quiz(1, "Fred was the man's last name that coined the phrase, 'Rock and Roll'.", false)
add_ox_quiz(1, "The Lone Ranger's horse was named Silver.", true)
add_ox_quiz(1, "Graham crackers were invented to suppress sexual desires.", true)
add_ox_quiz(1, "Robert Jenner discovered the rabies vaccine.", false)
add_ox_quiz(1, "World War II lasted from 1939 to 1945 in Europe.", true)
add_ox_quiz(1, "The word 'blackmail' has it's origin from the armor worn in medieval times.", true)
add_ox_quiz(1, "The Sea of Tranquility is a small sea in West Africa.", false)
add_ox_quiz(1, "3.14 are the first 3 digits of Pi. The next 3 digits are 018.", false)
add_ox_quiz(1, "No human has set foot on the lunar surface since Dec. 14, 1972.", true)
add_ox_quiz(1, "The `Lumbar Curve` is located in the leg on the human body.", false)
add_ox_quiz(1, "About 25% of the world's population is left-handed.", false)
add_ox_quiz(1, "The shortest war in history lasted just over two hours.", false)
add_ox_quiz(1, "Grilled Grass Carp increases attack speed by 20 for 10 mins.", true)
add_ox_quiz(1, "Grilled Eel increases strength by 10 for 10 min.", true)
add_ox_quiz(1, "To upgrade a Fishing Pole to +20 you need a Fishing Pole +8 with 420 points.", false)
add_ox_quiz(1, "You can wear Wedding Dress if you are a lvl 15 female warrior.", false)
add_ox_quiz(1, "Wooden Shoes+9 gives 15% to movement speed and 10% of poison resistance.", false)
add_ox_quiz(1, "You can use Dragon God Blessing scroll to upgrade items.", true)
add_ox_quiz(1, "Dark Queen Spider is lvl 65.", false)
add_ox_quiz(1, "Golden retrievers are the world's most popular breed of dog (in numbers purchased).", false)
add_ox_quiz(1, "The winds of a hurricane can reach up to 200 miles an hour or more.", true)
add_ox_quiz(1, "The first Queen of England to write and publish a book under her own name was Catherine Parr.", true)
add_ox_quiz(1, "The Trans-Siberian railway line is the longest in the world.", true)
add_ox_quiz(1, "There are only 25 countries world-wide in which people drive on the left-hand side of the road.", false)
add_ox_quiz(1, "The Remarkables is an impressive mountain range in New Zealand.", true)
add_ox_quiz(1, "Grilled Crucian Carp restores 180 sp.", false)
add_ox_quiz(1, "Photography was invented by the Lumiere brothers.", false)
add_ox_quiz(1, "Richard Nixon resigned in 1976 because of the Watergate Scandal.", false)
add_ox_quiz(1, "Baseball is one of the most popular sports in Venezuela.", true)
add_ox_quiz(1, "Singapore is known as the City of Tigers.", false)
add_ox_quiz(1, "Dragon God Blessing recovers 100% of your HP and your SP.", false)
add_ox_quiz(1, "You need Unknown Medicine to upgrade a Magic Bell to +5.", true)
add_ox_quiz(1, "To hide your rank you need an Escapee's Cape.", true)
add_ox_quiz(1, "The distance around a circle is known as circumference.", true)
add_ox_quiz(1, "The Juventus rugby team is known as 'La Vecchia Signora' (The Old Lady).", false)
add_ox_quiz(1, "The Singaporean flag is white and red.", true)
add_ox_quiz(1, "The 1992 Olympics were held in Barcelona.", true)
add_ox_quiz(1, "Cursed Alpha Blue Wolf can drop Full Moon Sword.", true)
add_ox_quiz(1, "Muslim law forbids eating lamb meat.", false)
add_ox_quiz(1, "Soon has strong feelings for Yu-Rang.", false)
add_ox_quiz(1, "Your feet are bigger in the morning than the rest of the day.", false)
add_ox_quiz(1, "If coloring weren't added to Coca-Cola, it would be Blue.", false)
add_ox_quiz(1, "The Red Bull drink was created in Austria.", true)
add_ox_quiz(1, "The Tropic of Capricorn is in the southern hemisphere.", true)
add_ox_quiz(1, "Sylvester Stallone wrote the script for the Rocky film saga himself.", true)
add_ox_quiz(1, "The Infernal guild has an Accessories Blacksmith.", true)
add_ox_quiz(1, "2 snake tails and clams are needed to upgrade silver sword to +9.", false)
add_ox_quiz(1, "2 yeti furs and blue pearls are needed to upgrade a battle sword to +8.", false)
add_ox_quiz(1, "2 ice marbles and red pearls are needed to upgrade a golden bug bell to +9.", false)
add_ox_quiz(1, "2 ice marbles + and red pearls are needed to upgrade a golden bug bell to +9.", true)
add_ox_quiz(1, "Curse book and white pearl are needed to upgrade a golden bug bell to +7.", false)
add_ox_quiz(1, "`Morna` is a musical style from Cabo Verde.", true)
add_ox_quiz(1, "Waryong is located in Asmodia.", true)
add_ox_quiz(1, "Waryong is located in Pandemonia.", false)
add_ox_quiz(1, "With King powers you can summon a Elite Nine Tails.", false)
add_ox_quiz(1, "The Lord of the Rings was written in stages between 1937 and 1949.", true)
add_ox_quiz(1, "The Guardian is a British national daily newspaper.", true)
add_ox_quiz(1, "The capital of Vietnam is Saigon.", false)
add_ox_quiz(1, "The capital of Australia is Canberra.", true)
add_ox_quiz(1, "The Pitcairn Islands are the least populated country in the world.", true)
add_ox_quiz(1, "Harvard is the oldest college in the United States.", true)
add_ox_quiz(1, "The berries on mistletoe are white?.", true)
add_ox_quiz(1, "The earth rotates in the same direction as it orbits the Sun.", true)
add_ox_quiz(1, "The 'sport of kings' is horse racing.", false)
add_ox_quiz(1, "London, Paris, Geneva, Madrid: All of them are European capital cities.", false)
add_ox_quiz(1, "The moon is larger in surface area than the United States.", true)
add_ox_quiz(1, "Seoul was chosen as the site of the 1988 summer Olympics.", true)
add_ox_quiz(1, "Ziggy Marley was the lead singer of the reggae supergroup, 'The Whalers'.", false)
add_ox_quiz(1, "A pentadecagon is a 2-D shape with 15 sides.", true)
add_ox_quiz(1, "Tornadoes seldom move at speeds greater than 40 mph.", true)
add_ox_quiz(1, "Pasta originated in Asia and was brought to Italy from China by Marco Polo.", true)
add_ox_quiz(1, "Adults have more bones than babies do.", false)
add_ox_quiz(1, "Diagonals drawn from opposing corners of a rectangle will always bisect each other.", true)
add_ox_quiz(1, "Studies have shown that the main reason people lie is for their own amusement.", false)
add_ox_quiz(1, "Stuttering and stammering are, essentially, the same thing.", true)
add_ox_quiz(1, "The youngest ever Pope was only 10 years old.", false)
add_ox_quiz(1, "A man's heart beats faster than a woman's (on average).", false)
add_ox_quiz(1, "If a month starts on a Sunday it will contain Friday the 13th.", true)
add_ox_quiz(1, "No country on mainland Africa uses all of the five vowels in its name.", false)
add_ox_quiz(1, "Grilled Perch restores unusual situation.", true)
add_ox_quiz(1, "Grilled Catfish restores 500 hp.", false)
add_ox_quiz(1, "Tiger earrings increase damage by 600.", false)
add_ox_quiz(1, "You can wear Tuxedo if you are a lvl 75 male mage.", true)
add_ox_quiz(1, "The Dutch football team of the 70s was known as the `clockwork orange`.", true)
add_ox_quiz(1, "Golf courses usually have 28 holes.", false)
add_ox_quiz(1, "Portugal is the world's first manufacturer of the bottle cork.", true)
add_ox_quiz(1, "Footballer Cristiano Ronaldo was born in the Azores islands.", false)
add_ox_quiz(1, "Muslim law forbids eating fish.", false)
add_ox_quiz(1, "Oasis and Swid are two bands of the Britpop movement.", false)
add_ox_quiz(1, "The Great Wall of China is one of the 7 Wonders of the Modern World.", true)
add_ox_quiz(1, "With M1 Leadership you can increase the HP of one party member.", true)
add_ox_quiz(1, "You need to hunt 20 Fighting Tigers in the 20th horse quest.", true)
add_ox_quiz(1, "Trinidad and Tobago competed in the 2009 FIFA World Cup sub 20.", true)
add_ox_quiz(1, "The port of Baku is situated in Russia.", true)
add_ox_quiz(1, "USB stands for `Universal Standard Bus`.", false)
add_ox_quiz(1, "Gouda cheese is of Dutch origin.", true)
add_ox_quiz(1, "You need be level 75 to rise to the 7th Demon Tower floor.", true)
add_ox_quiz(1, "Kurdistan is a country from the Middle East.", false)
add_ox_quiz(1, "Buddhism is the most practiced religion in Spain.", false)
add_ox_quiz(1, "The name of the Grandmaster Skill for Curing is Aid of Night.", false)
add_ox_quiz(1, "A pack-a-day smoker will lose approximately 4 teeth every 10 yrs.", false)
add_ox_quiz(1, "You can cry tears in outer space without a space suit.", false)
add_ox_quiz(1, "Most species of ants like to make their burrows beneath stone.", true)
add_ox_quiz(1, "It is common to find more than a half million ant-eaters in a single nest.", false)
add_ox_quiz(1, "Originally, Latins were the inhabitants of the Latium region in Italy.", true)
add_ox_quiz(1, "Animal film star Flipper was in fact played by several different dolphins.", true)
add_ox_quiz(1, "2 bear gall + is needed to upgrade a silver bell to +7.", true)
add_ox_quiz(1, "2 scorpion tails and clams are needed to upgrade a jade bell to +8.", false)
add_ox_quiz(1, "Leo Messi is the highest paid sportsman in the world.", false)
add_ox_quiz(1, "The Afrikaans language is closely based upon Dutch.", true)
add_ox_quiz(1, "Mount Olympus is the highest mountain in Greece, located on the border with Macedonia.", true)
add_ox_quiz(1, "Dr. Robin Cookis is best known for combining medical writing with the thriller genre.", true)
add_ox_quiz(1, "Stephen Smith Hawking is an English theoretical physicist and cosmologist.", false)
add_ox_quiz(1, "The world's largest theft occurred in Brazil and stole 72 million dollars.", true)
add_ox_quiz(1, "The most expensive hotel room in the world is the Bridge Suite, Atlantis Hotel, Bahamas.", true)
add_ox_quiz(1, "Sir Winston Churchill was Minister of the Navy of Great Britain during the First World War.", true)
add_ox_quiz(1, "Sylvester Stallone has been nominated for both an Academy Award for 'Best Actor' and a Razzie Award for 'Worst Actor' for playing the same role.", true)
add_ox_quiz(1, "Charlie Chaplin once won third prize in a Charlie Chaplin look alike contest.", true)
add_ox_quiz(1, "President F. D. Roosevelt declared December 7, 1941 the 'Day of Infamy'.", true)
add_ox_quiz(1, "The first Best Actress Academy Award went to Lillian Gish.", false)
add_ox_quiz(1, "The Tower of London is on the South bank of the River Thames.", false)
add_ox_quiz(1, "The first elevator was erected in 1743 in the Palace of Versailles.", true)
add_ox_quiz(1, "There is an island called Bikini Atoll where the U.S. tested nuclear bombs.", true)
add_ox_quiz(1, "The following books are in the Old Testament of the Bible: Genesis, Exodus, Numbers and Leviticus.", true)
add_ox_quiz(1, "In Britain, you can only shoot a Welsh person with a bow and arrow inside the city walls and after midnight.", false)
add_ox_quiz(1, "The dolphin does not require sleep as it is on the move constantly.", false)
add_ox_quiz(1, "D'Artagnan was one of the original 'Three Musketeers'.", false)
add_ox_quiz(1, "The bones of a pigeon are so light that they weigh less than its feathers.", true)
add_ox_quiz(1, "Actor Jack Lemmon was born in a hospital elevator in Boston, USA.", true)
add_ox_quiz(1, "In the mission of the biologist's lvl 85 you have to deliver 30 Giant Symbols.", false)
add_ox_quiz(1, "Grilled Loach gives the player invisibility for 5 mins.", true)
add_ox_quiz(1, "To upgrade a Pickaxe to +1 you need a Pickaxe+0 with 60000 points.", false)
add_ox_quiz(1, "To upgrade a Pickaxe to +6 you need a Pickaxe+5 with 19200 points.", false)
add_ox_quiz(1, "To upgrade a Fishing Pole to +9 you need a Fishing Pole +8 with 200 points.", true)
add_ox_quiz(1, "Wooden Shoes+9 gives 15% to movement speed and 10% of lightning resistance.", true)
add_ox_quiz(1, "Dark Queen Spider is lvl 60.", true)
add_ox_quiz(1, "The Zulu tribe live mostly in South America.", false)
add_ox_quiz(1, "People from New Zealand are informally known as kiwis.", true)
add_ox_quiz(1, "The most spoken language in Singapore is Chinese.", false)
add_ox_quiz(1, "California is the 4th largest spoon producer in the world.", false)
add_ox_quiz(1, "The mercenaries are on Heaven Land.", false)
add_ox_quiz(1, "The Aqua Dragon level is 97.", true)
add_ox_quiz(1, "Tiger Earrings give you 300 AP for 20 hours.", true)
add_ox_quiz(1, "Rockhopper, King and Emperor are all types of penguins.", true)
add_ox_quiz(1, "The Queen of England who married her mother-in-law was Catherine of Aragon.", false)
add_ox_quiz(1, "Adolf Hitler was born in Austria.", true)
add_ox_quiz(1, "Strong against Undead works well against Mu-Rang.", false)
add_ox_quiz(1, "Madonna's first single was 'Everybody' released in 1982.", true)
add_ox_quiz(1, "2010 is the Year of the Tiger in the Chinese calendar.", true)
add_ox_quiz(1, "The author of The Lord of the Rings is  J. R. R. Tolkien.", true)
add_ox_quiz(1, "The Vatican basilica was first built by Emperor Constantine.", true)
add_ox_quiz(1, "A Helm for level 21 +5 gives 33 of AC.", true)
add_ox_quiz(1, "Most of the European languages originated in North Africa.", false)
add_ox_quiz(1, "The winner of the first Ultimate Guild Tournament was the Resurrection guild.", true)
add_ox_quiz(1, "Quiche Lorraine is a popular dish from England.", false)
add_ox_quiz(1, "Clam and Snakeskin are needed to upgrade an Orchid Sword +8.", false)
add_ox_quiz(1, "The ball pen was invented by Ukrainian scientist Laszlo Biro.", false)
add_ox_quiz(1, "Michael Jackson owns the rights to the North Carolina State anthem.", false)
add_ox_quiz(1, "Humphrey Bogart was related to Princess Diana. They were 7th cousins.", true)
add_ox_quiz(1, "Trees grow from the top rather than from the bottom up.", true)
add_ox_quiz(1, "In Greek weddings, it's customary to break the dishes used in the reception.", true)
add_ox_quiz(1, "The first Russian Tzar was Peter the Great.", false)
add_ox_quiz(1, "The monkey is a sacred animal for the Hindu.", true)
add_ox_quiz(1, "Wyoming is the least populated state in the U.S.A.", true)
add_ox_quiz(1, "2x White Flag is needed to upgrade War Scythe to +5.", false)
add_ox_quiz(1, "Many people live in Jurong Island.", false)
add_ox_quiz(1, "Briton, an ancient Gaelic language, is still spoken in northwest Greece.", false)
add_ox_quiz(1, "Fear skill prevents any aggressive monster from attacking you.", false)
add_ox_quiz(1, "Dark Giant Tortoise can drop +5 stones.", true)
add_ox_quiz(1, "The Marx Brothers were Groucho, Chico and Harpo Marx.", false)
add_ox_quiz(1, "2 red pigtail ribbon + is needed to upgrade silver bell to +8.", false)
add_ox_quiz(1, "2 unknown talisman and clam are needed to upgrade a jade bell to +7.", false)
add_ox_quiz(1, "2 worm out black uniform + are needed to upgrade a iron fan to +9.", true)
add_ox_quiz(1, "Ebony earrings +6 gives +400 HP.", true)
add_ox_quiz(1, "Ecstatic fan +7 gives 14% to Spell Speed.", false)
add_ox_quiz(1, "Tiziano painted the famous `Mona Lisa`.", false)
add_ox_quiz(1, "Beethoven composed music even after becoming totally deaf.", true)
add_ox_quiz(1, "With King powers you can summon a Death Reaper.", false)
add_ox_quiz(1, "Kings can only teleport a player once in a minute.", true)
add_ox_quiz(1, "The current queen of the Netherlands is Queen Juliana.", false)
add_ox_quiz(1, "You can win TEC Points in the Guild Tournament.", false)
add_ox_quiz(1, "The novel Charlotte Brönte is written by Jane Eyre.", false)
add_ox_quiz(1, "Michael Jordan was born in Brooklyn, New York.", true)
add_ox_quiz(1, "Alberto del Rio has won the Royal Rumble 2011.", true)
add_ox_quiz(1, "Mount Olympus is the tallest known volcano in the Solar System.", true)
add_ox_quiz(1, "To get the 4th uriel´s page you have to kill Desert Outlaws.", false)
add_ox_quiz(1, "The Iliad is an epic poem in dactylic hexameters, traditionally attributed to Homer.", true)
add_ox_quiz(1, "You need Snake Tail+ to upgrade a level 26 armor to +5.", false)
add_ox_quiz(1, "The World War II started in 1929.", true)
add_ox_quiz(1, "The largest airport in the world is in Iraq.", false)
add_ox_quiz(1, "The capital of Morocco is Rabat.", true)
add_ox_quiz(1, "Sierra Leone's capital is Freetown.", true)
add_ox_quiz(1, "China is the most populated country in the world.", true)
add_ox_quiz(1, "The term RAM means Random Access Memory.", true)
add_ox_quiz(1, "The term SQL is an acronym for Structured Query Language.", true)
add_ox_quiz(1, "The term BBC is an acronym for British Broadcasting Corporation.", true)
add_ox_quiz(1, "The German soccer team has 3 world cups under its belt.", true)
add_ox_quiz(1, "The Sultan of Brunei's birthday party was most expensive in the world.", true)
add_ox_quiz(1, "Spain has a land border with four different countries.", true)
add_ox_quiz(1, "Like humans, whales breathe air.", true)
add_ox_quiz(1, "The Wright Brothers' plane was called Kitty Hawk.", false)
add_ox_quiz(1, "Leningrad (St. Petersburg) suffered a siege of well over two years in World War II.", true)
add_ox_quiz(1, "There is such a country known as Benin.", true)
add_ox_quiz(1, "The country Cameroon borders the Congo.", true)
add_ox_quiz(1, "Strawberries have more Vitamin C than oranges.", true)
add_ox_quiz(1, "Candytuft is a kind of sugared sweet.", false)
add_ox_quiz(1, "In 'Gulliver's Travels', Jonathan Swift described the two moons of Mars, Phobos and Deimos, giving their exact size and speed of rotation.", true)
add_ox_quiz(1, "Abraham Lincoln, Woodrow Wilson, Richard Nixon, Gerald Ford: All of them were US Presidents.", true)
add_ox_quiz(1, "Peugeot, Renault, Seat, Citroen: All of them are French car manufacturers.", false)
add_ox_quiz(1, "Dennis the Menace's favorite beverage is milk.", false)
add_ox_quiz(1, "Before the book 'Peter Pan', the name Wendy had never been used.", false)
add_ox_quiz(1, "During World War II, the Oscars were made of plaster.", true)
add_ox_quiz(1, "Australia's capital in 1901 was Melbourne.", true)
add_ox_quiz(1, "`The Lord of the Rings` Trilogy was filmed entirely in New Zealand.", true)
add_ox_quiz(1, "The tin can was invented before the tin can opener.", true)
add_ox_quiz(1, "Fryer was the name given to the Wright Brother's airplane.", false)
add_ox_quiz(1, "Batman and Robin's Bat Cave is 14 miles from Gotham City.", true)
add_ox_quiz(1, "If you have an I.Q. below 25 you are considered an idiot.", true)
add_ox_quiz(1, "Your ears and your nose lengthen throughout your life partly because the cartilage loses elasticity.", true)
add_ox_quiz(1, "Pearls melt in vinegar.", true)
add_ox_quiz(1, "Ian Fleming wrote 'Chitty Chitty Bang Bang'.", true)
add_ox_quiz(1, "The distance from the foul line to the headpin in bowling is 70 feet.", false)
add_ox_quiz(1, "The Easy-Bake Oven was the first toy to be advertised on television.", false)
add_ox_quiz(1, "If you swallow chewing gum, it doesn't pass through the digestive system for seven years.", false)
add_ox_quiz(1, "Rubies and sapphires are exactly alike except in color.", true)
add_ox_quiz(1, "The African rhinoceros has 2 horns on its head.", true)
add_ox_quiz(1, "Billy the Kid's real name was William H. Bologna.", false)
add_ox_quiz(1, "Alfred was Bruce Wayne's butler on the T.V. series 'Batman'.", true)
add_ox_quiz(1, "Alfred Hitchcock finally won an Academy Award for directing 'Psycho'.", false)
add_ox_quiz(1, "The Six Days War lasted just over six days.", false)
add_ox_quiz(1, "The oak tree is classified as a 'softwood'.", false)
add_ox_quiz(1, "Hans Christian Andersen is the author of `The Little Mermaid`.", true)
add_ox_quiz(1, "Tomatoes are vegetables.", false)
add_ox_quiz(1, "Juan Ponce de Leon discovered Florida in 1513.", true)
add_ox_quiz(1, "The first sequel to win Best Picture at the Academy Awards was 'The Godfather Part II'.", true)
add_ox_quiz(1, "A cygnet is a baby dolphin.", false)
add_ox_quiz(1, "There is a town named Mars in Pennsylvania.", true)
add_ox_quiz(1, "Ninety percent of Canadians live within 600 km of the US border.", true)
add_ox_quiz(1, "Identical twins have the same fingerprints.", false)
add_ox_quiz(1, "James Arness (Matt Dillon) served in the U.S. Army in World War Two.", true)
add_ox_quiz(1, "All the bones in the human body connect to one another.", false)
add_ox_quiz(1, "King Akhenaten of Egypt was considered even more beautiful than his wife, Queen Nefertiti.", false)
add_ox_quiz(1, "Jade Bracelet+5 gives a 3% chance to restore sp.", true)
add_ox_quiz(1, "The film `The Princess Bride` was released in 1984.", false)
add_ox_quiz(1, "The vocabulary of the average person is consists of 5000 to 6000 words.", true)
add_ox_quiz(1, "Most lipsticks contain fish scales.", true)
add_ox_quiz(1, "The word 'right' has 5 letters in it.", true)
add_ox_quiz(1, "A Bactrian camel has two humps on its back.", true)
add_ox_quiz(1, "A baby cannot blush.", true)
add_ox_quiz(1, "Before it was completed, one of the faces on Mount Rushmore was completely blasted away and relocated.", true)
add_ox_quiz(1, "Only the Australian koala plus great apes and humans have unique fingerprints.", true)
add_ox_quiz(1, "Walt Disney was cryogenically frozen after death.", false)
add_ox_quiz(1, "In the book of 'The Wizard of Oz', Dorothy wears silver shoes.", true)
add_ox_quiz(1, "Bulls will only charge at the color red.", false)
add_ox_quiz(1, "The highest measurement possible on the Richter scale (earthquake force) is 10.", false)
add_ox_quiz(1, "Our nose, eyes and ears never stop growing until the day we die.", false)
add_ox_quiz(1, "The exact translation of the origin of the word 'check-mate' is 'the king is captured'.", false)
add_ox_quiz(1, "No word in the English language (British) has five consecutive letters that are vowels.", false)
add_ox_quiz(1, "Although flightless, Kiwi birds have wings.", true)
add_ox_quiz(1, "The anticoagulant found in the saliva of vampire bats is called draculin.", true)
add_ox_quiz(1, "Most people cannot lick their elbow or stick their elbow in their ear.", true)
add_ox_quiz(1, "The average human head contains enough iron to make a 7,62cm nail.", true)
add_ox_quiz(1, "Grilled Mandarin Fish restores 180 hp.", false)
add_ox_quiz(1, "Grilled Salmon restores 350 hp.", false)
add_ox_quiz(1, "Grilled Carp increases attack speed by 20 for 10 mins.", false)
add_ox_quiz(1, "Grilled Rainbow Trout restores 600 hp.", false)
add_ox_quiz(1, "Grilled Tilapia restores 230 sp.", true)
add_ox_quiz(1, "King Spider is lvl 60.", false)
add_ox_quiz(1, "Grilled Tenchi restores 230 hp.", true)
add_ox_quiz(1, "To upgrade a Pickaxe to +3 you need a Pickaxe+2 with 24000 points.", true)
add_ox_quiz(1, "To upgrade a Pickaxe to +5 you need a Pickaxe+4 with 9600 points.", false)
add_ox_quiz(1, "To upgrade a Pickaxe to +7 you need a Pickaxe+6 with 38400 points.", false)
add_ox_quiz(1, "Fishing Pole can be upgraded to +10", true)
add_ox_quiz(1, "Dragon earrings increase hp by 300.", false)
add_ox_quiz(1, "You can wear Tuxedo if you are a lvl 75 female mage.", false)
add_ox_quiz(1, "You can wear Black Tunic+8 if you are lvl 68 female archer.", false)
add_ox_quiz(1, "You need ice marble x2 and blue pearl to upgrade Black Tunic from +8 to +9.", false)
add_ox_quiz(1, "Copper Bracelet+ increases max sp in 180.", true)
add_ox_quiz(1, "You can use Dragon God Blessing spell to upgrade items.", false)
add_ox_quiz(1, "Queen Spider is lvl 60.", true)
add_ox_quiz(1, "No animal eats bees.", false)
add_ox_quiz(1, "The United States bought Florida from England.", false)
add_ox_quiz(1, "Walt Disney's middle name was Enoch.", false)
add_ox_quiz(1, "Da Vinci cut off his ear and gave it to his girlfriend.", false)
add_ox_quiz(1, "George Washington is noted for having almost perfect teeth.", false)
add_ox_quiz(1, "Uncle Sam was a fictitious person created by soldiers.", false)
add_ox_quiz(1, "Mahatma Gandhi was assassinated on 12th March 1948.", false)
add_ox_quiz(1, "Eating too many carrots can cause a person to turn orange.", true)
add_ox_quiz(1, "The only man-made structures that can be seen from outer space are the Great Pyramids.", false)
add_ox_quiz(1, "A fossil fuel is defined a hydrocarbon deposit, derived from organisms of a previous time and used for fuel.", true)
add_ox_quiz(1, "The Uncle Sam recruiting poster 'I Want You' first appeared in World War II.", false)
add_ox_quiz(1, "Henry Ford's profit on his Model T Ford was only about $2.00.", true)
add_ox_quiz(1, "The oldest rock on Earth was found by geologists in the outback of Australia in January, 2001.", true)
add_ox_quiz(1, "Saint Patrick, the patron saint of Ireland, was not born in Ireland.", true)
add_ox_quiz(1, "No words in the English language form a perfect rhyme with month, orange, or purple.", true)
add_ox_quiz(1, "Windshield wipers were invented by a woman.", true)
add_ox_quiz(1, "The movie 'American Beauty' won the Oscar for Best Picture.", true)
add_ox_quiz(1, "The martial art of tae kwon do originated from Japan.", false)
add_ox_quiz(1, "The Egyptians were the first to discover the earliest form of cement.", true)
add_ox_quiz(1, "Some mammals actually lay eggs instead of giving birth in the usual manner of most mammals.", true)
add_ox_quiz(1, "Witches were never burned at the stake in Salem, MA.", true)
add_ox_quiz(1, "Diamond is the hardest naturally-occurring substance on earth.", true)
add_ox_quiz(1, "The first ship to use the 'SOS' signal was the Titanic.", false)
add_ox_quiz(1, "The pursuit of jumping off cliffs into the sea is termed 'tombstoning'.", true)
add_ox_quiz(1, "The word 'girl' never appears in the Bible (any translation).", false)
add_ox_quiz(1, "Other than humans, the only primate that can have blue eyes is the chimpanzee", false)
add_ox_quiz(1, "There are more germs on a toilet seat than a car steering wheel.", false)
add_ox_quiz(1, "You need to reach lvl70 o use a poison sword +6.", false)
add_ox_quiz(1, "Grilled Carp increases moving speed by 20 for 10 mins.", true)
add_ox_quiz(1, "Grilled Grass Carp increases spell speed by 20 for 10 mins.", false)
add_ox_quiz(1, "Grilled Rainbow Trout restores 800 hp.", false)
add_ox_quiz(1, "Grilled Pikes increase strength by 10 for 10 min.", false)
add_ox_quiz(1, "To upgrade a Pickaxe to +1 you need a Pickaxe+0 with 6000 points.", true)
add_ox_quiz(1, "To upgrade a Pickaxe to +2 you need a Pickaxe+1 with 12000 points.", true)
add_ox_quiz(1, "To upgrade a Pickaxe to +4 you need a Pickaxe+3 with 4800 points.", false)
add_ox_quiz(1, "To upgrade a Pickaxe to +8 you need a Pickaxe+7 with 768000 points.", true)
add_ox_quiz(1, "You can wear Tuxedo if you are a lvl 25 female mage.", false)
add_ox_quiz(1, "You can wear Wedding Dress if you are a lvl 35 male warrior.", false)
add_ox_quiz(1, "You need a Black Tunic+8, ice marble x2 and red pearl to get Black Tunic +9.", true)
add_ox_quiz(1, "Queen Spider is lvl 60.", true)
add_ox_quiz(1, "You need to read 155 GuiGu Art of War correctly to reach P Leadership.", true)
add_ox_quiz(1, "Four bridges connect Singapore to Malaysia.", false)
add_ox_quiz(1, "Elite Vile Demon King can drop Ecstatic Fan.", false)
add_ox_quiz(1, "With M1 Leadership you can increase the Attack Power of one party member.", true)
add_ox_quiz(1, "Pierce doesn't work for magical attacks.", true)
add_ox_quiz(1, "2 curse books  and a clam are needed to upgrade a jade bell to +9.", true)
add_ox_quiz(1, "2 leafs and white pearls are needed to upgrade a golden bug bell to +7.", true)
add_ox_quiz(1, "2 white tiger hide are needed to upgrade an iron fan to +8.", true)
add_ox_quiz(1, "Titan Enchantment is a Sura Skill.", false)
add_ox_quiz(1, "Blue dress +5 gives 44 of AC.", false)
add_ox_quiz(1, "Ebony earrings +6 gives +450 HP.", false)
add_ox_quiz(1, "You can use White Flag to make mobs run away from you.", false)
add_ox_quiz(1, "Marsupials live only in Asia and Oceania.", false)
add_ox_quiz(1, "Kings can boost the attacking power of all the kingdom forces in Nation War.", true)
add_ox_quiz(1, "The capitol city of Sri Lanka is Colombo.", false)
add_ox_quiz(1, "During Hunter's Hour, drop rate is increased to 500%.", true)
add_ox_quiz(1, "The real name of Pele is Edson Arantes do Nascimento.", true)
add_ox_quiz(1, "Africa is the world's second-largest and second most-populous continent.", true)
add_ox_quiz(1, "The term RADAR was coined in 1841 as an acronym for Radio Detection and Ranging.", false)
add_ox_quiz(1, "Black Magic Armor +9 gives 20% to movement speed.", false)
add_ox_quiz(1, "Mount Olympus is one of the Himalayan Mountains.", false)
add_ox_quiz(1, "Bleach is a Japanese shounen manga series written and illustrated by Noriaki 'Tite' Kubo.", true)
add_ox_quiz(1, "La Divina Commedia is an epic poem written by Dante Philipo between 1308 and his death in 1321.", false)
add_ox_quiz(1, "Your rank is 'Good' when you have 8050 rank points.", false)
add_ox_quiz(1, "Pearl Jam is a rock band from Canada.", false)
add_ox_quiz(1, "Latin is a dead language.", true)
add_ox_quiz(1, "The capital of Canada is Toronto.", false)
add_ox_quiz(1, "The capital of Romania is Budapest.", false)
add_ox_quiz(1, "The capital of New Zealand is Wellington.", true)
add_ox_quiz(1, "The tallest known dinosaur is the Sauroposeidon.", true)
add_ox_quiz(1, "The term RAM means Random Acting Memory.", false)
add_ox_quiz(1, "The term CD-ROM is an acronym for Compact Disc read-only memory.", true)
add_ox_quiz(1, "The Spanish soccer team became world champions for the second time in 2010.", false)
add_ox_quiz(1, "The Sultan of Brunei's birthday party was more expensive in the world.", true)
add_ox_quiz(1, "Al Capone was arrested by the FBI for illegal alcohol sales.", false)
add_ox_quiz(1, "Mount Aconcagua is the tallest mountain in the Americas.", true)
add_ox_quiz(1, "The leopard is the fastest mammal on earth.", false)
add_ox_quiz(1, "New Amsterdam was the original name of New York.", true)
add_ox_quiz(1, "Saccharine is derived from coal.", true)
add_ox_quiz(1, "Algae is the world's largest oxygen producer.", true)
add_ox_quiz(1, "Minnesota, Wisconsin, Illinois, Arkansas: All of them are American states along the Mississippi River.", true)
add_ox_quiz(1, "Before becoming Governor of Texas, George W. Bush was co-owner of a professional baseball team.", true)
add_ox_quiz(1, "A rat can last longer without water than a camel.", true)
add_ox_quiz(1, "There are no known English words that rhyme with orange, purple and silver.", true)
add_ox_quiz(1, "Gabriel and Michael were the only two angels, mentioned by name, in the King James Bible.", false)
add_ox_quiz(1, "The 'Texas Theatre' was the Dallas movie house where Lee Harvey Oswald was captured after the shooting of J.F.K.", true)
add_ox_quiz(1, "The beautiful Olivia Newton John played the part of Sandy Olsson in `Grease II`.", false)
add_ox_quiz(1, "Absolute Zero is -459.67 degrees F.", true)
add_ox_quiz(1, "The maximum value for 'Strength against Sura' is 15%.", false)
add_ox_quiz(1, "Nine Tails can't be stunned.", false)
add_ox_quiz(1, "The original name of Gollum from Lord of the Rings was Gimli.", false)
add_ox_quiz(1, "The didgeridoo is a primitive Australian instrument.", true)
add_ox_quiz(1, "Seismologists study earthquakes.", true)
add_ox_quiz(1, "Ulysses was written by James Joyce.", true)
add_ox_quiz(1, "Evanescence is a Canadian gothic metal band.", false)
add_ox_quiz(1, "Caipirinha is Brazil's national cocktail drink.", true)
add_ox_quiz(1, "The 1988 Olympics were held in South Korea.", true)
add_ox_quiz(1, "America was discovered by the Vikings long before Christopher Columbus.", true)
add_ox_quiz(1, "One of the inhabitants of the African continent is the penguin.", true)
add_ox_quiz(1, "Nasi Goreng is a popular dish from Polynesia.", false)
add_ox_quiz(1, "Titan Enchantment is a Mage Skill.", true)
add_ox_quiz(1, "Leopard Pills give +60 of movement speed for 30 minutes.", true)
add_ox_quiz(1, "Jungrang is on Pandemonia Kingdom.", true)
add_ox_quiz(1, "A Helm for level 41 +4 gives 39 of AC.", false)
add_ox_quiz(1, "Pearl Jam is a dance band from United States.", false)
add_ox_quiz(1, "The statue of Liberty was constructed in France.", true)
add_ox_quiz(1, "Your rank is 'Good' when you have 6000 points.", true)
add_ox_quiz(1, "The popular detective character created by Agatha Christie is Sherlock Holmes.", false)
add_ox_quiz(1, "The tallest statue in the world is the Statue of Liberty in New York.", false)
add_ox_quiz(1, "In Netherlands, popular legend says Santa Claus was a Spanish bishop.", true)
add_ox_quiz(1, "Paul McCartney once said `The Beatles are more famous than God himself`.", false)
add_ox_quiz(1, "England is the only country where cars drive on the left.", false)
add_ox_quiz(1, "The 1976 Soccer World Cup was held in Argentina.", false)
add_ox_quiz(1, "Singapore is the third smallest sovereign country in the world.", true)
add_ox_quiz(1, "You need to read 53 books successfully to get a G1 skill.", false)
add_ox_quiz(1, "Slovenia is a member of the European Union.", true)
add_ox_quiz(1, "Godzilla is a legendary monster in Portuguese culture.", false)
add_ox_quiz(1, "The coldest inhabited place on earth is located in Russia.", true)
add_ox_quiz(1, "Ray Bradbury wrote the novel Fahrenheit 911.", false)
add_ox_quiz(1, "The winner of the first Ultimate Guild Tournament was the HellBound guild.", false)
add_ox_quiz(1, "French is still spoken in the north American state of Mexico.", false)
add_ox_quiz(1, "Bob Marley died in Miami, Florida in 1981.", true)
add_ox_quiz(1, "Machu Picchu is the ancient capitol city of Inca Empire.", true)
add_ox_quiz(1, "2 Orc Tooth+ and Clam are needed to upgrade Cat Bite Knife +9.", true)
add_ox_quiz(1, "Name of Grandmaster Skill for Fear is Horror.", false)
add_ox_quiz(1, "There are 8 fishermen in Youngan Area.", false)
add_ox_quiz(1, "Fire Signal is a level 100 npc.", false)
add_ox_quiz(1, "When you sneeze, all bodily functions stop, even your heart!.", true)
add_ox_quiz(1, "The first Harley Davidson motorcycle built in 1903 used a tomato can for a carburetor.", true)
add_ox_quiz(1, "The average housefly lives for two weeks.", true)
add_ox_quiz(1, "Arrow Resistance cannot be a bonus in a necklace.", false)
add_ox_quiz(1, "The purpose of flowers is to give beauty.", false)
add_ox_quiz(1, "The Monarch butterfly must have the milkweed plant to die.", false)
add_ox_quiz(1, "There are many less kinds of insects in the world than any other creature.", false)
add_ox_quiz(1, "The three pyramids of Giza were built for Pharaohs Cheops, Khefre and Menkaure.", true)
add_ox_quiz(1, "Uruguay won the soccer World Cup four times.", true)
add_ox_quiz(1, "Scotland is the home of golf.", true)
add_ox_quiz(1, "Computer Operating Systems were invented by Microsoft.", false)
add_ox_quiz(1, "Don Quixote was written by Miguel de Cervantes between 1705 and 1715.", false)
add_ox_quiz(1, "The president of FIFA is Joseph S.Blatter.", true)
add_ox_quiz(1, "Your rank is 'Aggressive' when your rank points reach -4000.", false)
add_ox_quiz(1, "Steel is an alloy of iron and carbon.", true)
add_ox_quiz(1, "The Damnation Guild has an Armor Blacksmith.", false)
add_ox_quiz(1, "A Jade Necklace +2 gives 8% of Spell Speed.", true)
add_ox_quiz(1, "Most of the Turkish population is Islamic.", true)
add_ox_quiz(1, "The World War I started in 1939.", false)
add_ox_quiz(1, "Singapore was founded by Sir Thomas Stamford Lockes.", false)
add_ox_quiz(1, "The river which carries the lowest quantity of water into the sea is the Amazon River.", false)
add_ox_quiz(1, "Scotland is the home of golf.", true)
add_ox_quiz(1, "Screws were invented in Ancient Greece.", true)
add_ox_quiz(1, "Mauna Loa, the worlds largest active volcano, is located in New Zealand.", false)
add_ox_quiz(1, "Florida has a Mediterranean climate.", false)
add_ox_quiz(1, "Computer Operating Systems were invented by Microsoft.", false)
add_ox_quiz(1, "Facebook is the largest social network in the Ethernet.", false)
add_ox_quiz(1, "Napoleon spent the late years of his life in the Saint Helen's Island.", true)
add_ox_quiz(1, "The car maker Fiat was founded in the Czech Republic.", false)
add_ox_quiz(1, "Don Quixote was written by Miguel de Cervantes between 1705 and 1715.", false)
add_ox_quiz(1, "To upgrade a Pickax to +3 you need a Pickax+2 with 2400 points.", false)
add_ox_quiz(1, "To upgrade a Pickax to +4 you need a Pickax+3 with 48000 points.", true)
add_ox_quiz(1, "To upgrade a Pickax to +5 you need a Pickax+4 with 96000 points.", true)
add_ox_quiz(1, "To upgrade a Pickax to +6 you need a Pickax+5 with 192000 points.", true)
add_ox_quiz(1, "To upgrade a Pickax to +7 you need a Pickax+6 with 384000 points.", true)
add_ox_quiz(1, "Fishing Pole can only reach +9.", false)
add_ox_quiz(1, "You can upgrade Fishing Pole to +20.", true)
add_ox_quiz(1, "To upgrade a Fishing Pole to +20 you need a Fishing Pole +19 with 400 points.", false)
add_ox_quiz(1, "Tiger earrings increase damage by 300.", true)
add_ox_quiz(1, "Dragon earrings increase defense by 300.", true)
add_ox_quiz(1, "Dragon earrings increase damage by 300.", false)
add_ox_quiz(1, "You can wear Tuxedo if you are lvl 25 male mage.", true)
add_ox_quiz(1, "You can wear Wedding Dress if you are lvl 25 female warrior.", true)
add_ox_quiz(1, "You can wear Black Tunic+8 if you are lvl 69 female mage.", true)
add_ox_quiz(1, "You need Black Tunic+7, ice marble x2 and red pearl to get Black Magic Armor +9.", false)
add_ox_quiz(1, "Jade Bracelet+5 gives a 3% chance to restore hp.", false)
add_ox_quiz(1, "If you use Blessing scroll and you fail to upgrade, your item will be degraded by 1.", true)
add_ox_quiz(1, "Singapore is known as the City of Lions.", true)
add_ox_quiz(1, "Eskimos fight each other by rubbing their noses.", false)
add_ox_quiz(1, "The president of FIFA is Joseph S.Blatter.", true)
add_ox_quiz(1, "Volleyball is played by 11 players on each side.", false)
add_ox_quiz(1, "The most common language in the Philippines is tagalog.", true)
add_ox_quiz(1, "The level of Grizzly Bear is 15.", true)
add_ox_quiz(1, "Tuxedo can be equipped from level 20.", false)
add_ox_quiz(1, "Heaven Tear Earrings +9 gives +14 of INT.", true)
add_ox_quiz(1, "'The Fugitive' starring Harrison Ford and Tommy Lee Jones, was based on a TV series of the same name.", true)
add_ox_quiz(1, "Laos' capital city is Vientiane.", true)
add_ox_quiz(1, "A snapper turtle can bite harder than a African Lion.", true)
add_ox_quiz(1, "The Dutch National football team has never won the World Championship before 2006.", true)
add_ox_quiz(1, "In Mexico, bullfights are traditionally held on Sundays.", true)
add_ox_quiz(1, "There are 36 black keys on a standard piano.", true)
add_ox_quiz(1, "Lucy Lawless, aka 'Xena, the Warrior Princess', was born in Wales.", false)
add_ox_quiz(1, "A 1997 episode of 'Pokemon' triggered epileptic seizures in over 600 children.", false)
add_ox_quiz(1, "A topless woman can be spotted in Disney's 'The Rescuers'.", true)
add_ox_quiz(1, "Bowling was first played in Italy.", false)
add_ox_quiz(1, "The Los Angeles Zoo has the largest collection of animals.", false)
add_ox_quiz(1, "On average, the 'eye muscles' move 300,000 times a day.", false)
add_ox_quiz(1, "The bulletproof vest was created by a woman.", true)
add_ox_quiz(1, "Cows have four-chambered stomachs.", true)
add_ox_quiz(1, "There are four leaves on a shamrock?.", false)
add_ox_quiz(1, "Adam's ale is a kind of beer?.", false)
add_ox_quiz(1, "There are 25 sheets of paper in a quire?.", true)
add_ox_quiz(1, "The Hague is in Holland?.", true)
add_ox_quiz(1, "A tine is the prong of a fork?.", true)
add_ox_quiz(1, "Sulphuric acid is another name for vitriol.", true)
add_ox_quiz(1, "James T. Kirk, Kathryn Janeway, Jean-Luc Picard, Jonathan Archer: All of them were ships' captains on 'Star Trek'.", true)
add_ox_quiz(1, "Call Me Ishmael' is the first line of the book 'Tom Sawyer'.", false)
add_ox_quiz(1, "In tennis, The Australian Open is one of the four tournaments making up the Grand Slam.", true)
add_ox_quiz(1, "Had Titanic not sunk on April 15, 1912, it was on a pace to break the speed record for Atlantic crossings.", false)
add_ox_quiz(1, "William Shakespeare was the first Poet Laureate.", false)
add_ox_quiz(1, "The oldest known animal was a tortoise, which lived to be 152 years old.", true)
add_ox_quiz(1, "A cat has more than double the amount of vertebrae in their spine than a human.", false)
add_ox_quiz(1, "Sherlock Holmes actually never said 'Elementary, my dear Watson'.", true)
add_ox_quiz(1, "Fingernails grow faster than toenails.", true)
add_ox_quiz(1, "The Canary Islands were formerly known as the 'Unfortunate Islands'.", false)
add_ox_quiz(1, "A young hedgehog is called a kitten.", false)
add_ox_quiz(1, "Windsor Castle is known as 'The Key to England'.", false)
add_ox_quiz(1, "Grilled Mandarin Fish restores 180 sp.", true)
add_ox_quiz(1, "Grilled Crucian Carp restores 180 hp.", true)
add_ox_quiz(1, "Grilled Grayling restores 350 hp.", true)
add_ox_quiz(1, "Grilled Salmon restores 350 sp.", true)
add_ox_quiz(1, "Grilled Grass Carp increases moving speed by 20 for 10 mins.", false)
add_ox_quiz(1, "Grilled Tilapia restores 230 hp.", false)
add_ox_quiz(1, "Grilled Tilapia restores 250 hp.", false)
add_ox_quiz(1, "Grilled Pikes increase agility by 10 for 10 min.", true)
add_ox_quiz(1, "Grilled Tenchi restores 230 sp.", false)
add_ox_quiz(1, "Grilled Tenchi restores 250 sp.", false)
add_ox_quiz(1, "Grilled Catfish restores 500 sp.", true)
add_ox_quiz(1, "Grilled Lotus Fish restores 500 sp.", false)
add_ox_quiz(1, "You can use Pickax+9 since lvl 30.", true)
add_ox_quiz(1, "To upgrade a Pickax to +1 you need a Pickax+0 with 600 points.", false)
add_ox_quiz(1, "Hans Christian Andersen is the author of 'The Ugly Duckling'.", true)
add_ox_quiz(1, "The first professional baseball team was the River City Bats.", false)
add_ox_quiz(1, "The country of Israel was created on 12th March, 1948.", false)
add_ox_quiz(1, "Large kangaroos can cover over 60 feet in one jump.", false)
add_ox_quiz(1, "Mick Jagger was once a student at the London School of Economics.", true)
add_ox_quiz(1, "Shanghai was once the largest city in the Communist world.", true)
add_ox_quiz(1, "Canada is the second largest country in terms of size/area.", true)
add_ox_quiz(1, "Ebay was founded by Pierre Omidyar.", true)
add_ox_quiz(1, "Stalactites come up from the ground.", false)
add_ox_quiz(1, "Bill Gates is the CEO of Dell Computers.", false)
add_ox_quiz(1, "The contrabassoon is a percussion instrument.", false)
add_ox_quiz(1, "Like humans, whales breathe air.", true)
add_ox_quiz(1, "Mount Vesuvius is an active volcano.", true)
add_ox_quiz(1, "The San Andreas Fault is 900 miles long.", false)
add_ox_quiz(1, "The clock in the Clock Tower (London Tower) is named Big Ben?.", false)
add_ox_quiz(1, "Charles Lindbergh and the Spirit of St. Louis returned to the United States on board a U.S. Navy ship?.", true)
add_ox_quiz(1, "The Erie Canal was 363 miles long when finished.", true)
add_ox_quiz(1, "The human race has managed to exterminate only two species of insects.", false)
add_ox_quiz(1, "Hollywood has never released a movie that had its sequel released the same year.", false)
add_ox_quiz(1, "One day on the planet Venus is actually longer than one year.", true)
add_ox_quiz(1, "One of the wondrous things that Marco Polo saw on his travels was a lump of coal.", true)
add_ox_quiz(1, "The first Triceratops bones were discovered in 1889.", true)
add_ox_quiz(1, "Chocolate syrup was used to simulate blood in the old 1931 vampire classic 'Dracula' by Universal.", false)
add_ox_quiz(1, "The biggest known volcano in the solar system is on Mars.", true)
add_ox_quiz(1, "If you sneeze when suddenly exposed to intensely bright light, you have photosynthesis.", false)
add_ox_quiz(1, "`Alexander the Great` was also known as `Alexander of Macedonia`.", true)
add_ox_quiz(1, "Only the Chinese Tiger is an endangered tiger species.", false)
add_ox_quiz(1, "There are three golf balls on the moon.", true)
add_ox_quiz(1, "The average person's right hand does 56% of the typing.", false)
add_ox_quiz(1, "A cat cannot move its jaw sideways.", true)
add_ox_quiz(1, "Heavyweight boxing legend Jack Johnson holds a patent on a wrench.", true)
add_ox_quiz(1, "Alphonse is the first name of actor Al Pacino.", false)
add_ox_quiz(1, "Nurse, doctor and matron are all varieties of shark.", false)
add_ox_quiz(1, "A light bulb at a fire station in Livermore, California, has been burning since 1901.", true)
add_ox_quiz(1, "Sudd is a name given to a swampy area in Sudan.", true)
add_ox_quiz(1, "Apollo 12 was the first manned landing in Mare Tranquillitatis.", false)
add_ox_quiz(1, "All turkeys gobble.", false)
add_ox_quiz(1, "Charles Lindbergh was the first person to fly across the Atlantic Ocean.", false)
add_ox_quiz(1, "More men stutter than women.", true)
add_ox_quiz(1, "S.O.S. stands for 'Save our Ship'.", false)
add_ox_quiz(1, "Dracula was a real person.", true)
add_ox_quiz(1, "`Frankenstein` was a monster made by a mad scientist.", false)
add_ox_quiz(1, "Barbie is 25cm tall.", true)
add_ox_quiz(1, "Natural propane gas has no odor.", true)
add_ox_quiz(1, "Celine Dion is one of fourteen children.", true)
add_ox_quiz(1, "The white part of a fingernail is called the 'luna'.", false)
add_ox_quiz(1, "Isaac Newton was an Anglican deacon.", true)
add_ox_quiz(1, "The most common first name in the world is Mohammed (Muhammad).", true)
add_ox_quiz(1, "The infinity sign is called a 'lemniscate'.", true)
add_ox_quiz(1, "It takes more than an hour to completely soft-boil an ostrich egg.", false)
add_ox_quiz(1, "A full-grown grizzly bear can run as fast as a horse.", true)
add_ox_quiz(1, "Dueling is legal in Paraguay as long as both parties are registered blood donors.", true)
add_ox_quiz(1, "Men can breastfeed.", true)
add_ox_quiz(1, "If a cockroach's head has been cut off, it can still live for around a week.", true)
add_ox_quiz(1, "Grilled Brook Trout restores 600 hp.", true)
add_ox_quiz(1, "Grilled Brook Trout restores 600 sp.", false)
add_ox_quiz(1, "Grilled Eel increases agility by 10 for 10 min.", false)
add_ox_quiz(1, "Grilled Rainbow Trout restores 600 sp.", true)
add_ox_quiz(1, "Your rank is 'Aggressive' when your rank points reach -4000.", false)
add_ox_quiz(1, "Lady Gaga is a natural blonde.", false)
add_ox_quiz(1, "Steel is an alloy of iron and carbon.", true)
add_ox_quiz(1, "The World War II started in 1939.", true)
add_ox_quiz(1, "Cats can see in total darkness.", false)
add_ox_quiz(1, "Nowadays, dolphin fishing is forbidden worldwide.", false)
add_ox_quiz(1, "The volcano Etna is located in an island near Japan.", false)
add_ox_quiz(1, "Butterflies have 6 legs and 1 pairs of wings.", false)
add_ox_quiz(1, "The largest ocean of the world is the Pacific ocean.", true)
add_ox_quiz(1, "The world's oldest known city is Damascus.", true)
add_ox_quiz(1, "The first Boxer to win 3 gold medals in Olympics was Mike Tyson.", false)
add_ox_quiz(1, "Many Spanish words come from the Arabic language.", true)
add_ox_quiz(1, "Rapper Tupac Shakur died in 1996.", true)
add_ox_quiz(1, "Gruyere cheese is of French origin.", false)
add_ox_quiz(1, "A Jade Necklace +2 gives 9% of Spell Speed ", false)
add_ox_quiz(1, "To prevent the dropping of items you need an Escapee's Cape", false)
add_ox_quiz(1, "Soccer is a popular women sport in the USA.", true)
add_ox_quiz(1, "FC Barcelona has never worn paid advertisement on their shirts.", true)
add_ox_quiz(1, "The largest airport in the world is in Saudi Arabia.", true)
add_ox_quiz(1, "Norwegian Roald Amundsen was the first human to reach the North Pole.", false)
add_ox_quiz(1, "Most of the Turkish population is Islamic.", false)
add_ox_quiz(1, "Sylvester Stallone was born in Italy.", false)
add_ox_quiz(1, "Los Angeles is on the Pacific Daylight Timezone.", true)
add_ox_quiz(1, "It's customary to chew coca leaves in Argentina.", false)
add_ox_quiz(1, "Jamaican coffee is amongst the worst in the world.", false)
add_ox_quiz(1, "2011 is the year of the Rabbit in the Chinese calendar.", true)
add_ox_quiz(1, "Greenland received this name because it was colder when discovered than it is today.", false)
add_ox_quiz(1, "The level of Young-Ji is 21.", true)
add_ox_quiz(1, "In Metin2 there are 56 types of skill Books.", false)
add_ox_quiz(1, "Black Steel Armor +7 can be worn from level 68.", false)
add_ox_quiz(1, "Gold is one of the main attractions for tourists in Singapore.", false)
add_ox_quiz(1, "Arnold Schwarzenegger became governor of California in 2003.", true)
add_ox_quiz(1, "In the level 21 horse quest you need to kill 150 Demon Spearmen.", false)
add_ox_quiz(1, "The Aquarius drink is made by Pepsi.", false)
add_ox_quiz(1, "The coldest inhabited place on earth is located in Greenland.", false)
add_ox_quiz(1, "Norway is a member of the European Union.", false)
add_ox_quiz(1, "China was runner-up in the Football World Cup in 1954.", false)
add_ox_quiz(1, "The official language in Malaysia is Malay.", true)
add_ox_quiz(1, "Ray Bradbury wrote the novel Fahrenheit 451.", true)
add_ox_quiz(1, "Hattie McDaniel was the first black actress to receive an Oscar for her role.", true)
add_ox_quiz(1, "Ethiopia has a strong Islamic community.", false)
add_ox_quiz(1, "The whole Dutch province of Friesland is built in terrain gained from the sea.", false)
add_ox_quiz(1, "In the level 21 horse quest you need to kill 300 Demon Archers.", false)
add_ox_quiz(1, "Stanley Matthews retired as a professional soccer player at the age of 60.", false)
add_ox_quiz(1, "Einstein was born in Ulm in 1879.", true)
add_ox_quiz(1, "Warrior's Symbol and Blue Pearl are needed to upgrade Half Moon Sword +8", false)
add_ox_quiz(1, "Name of Master Skill for Stealth is Silent Shadows", false)
add_ox_quiz(1, "Name of Grandmaster Skill for Berserk is Fury", false)
add_ox_quiz(1, "There are 8 fishermen in Bokjung Area", false)
add_ox_quiz(1, "NPC Nakajima is at co-ordinate 535 , 894 in Bakra Area.", false)
add_ox_quiz(1, "Reborn Chief Orc is level 60.", false)
add_ox_quiz(1, "You need to collect 25 Ghost Tree Branch for Cheagirab's level 80 collection quest.", false)
add_ox_quiz(1, "The toothbrush was invented in 1598.", false)
add_ox_quiz(1, "Most of us have eaten a spider in our sleep.", true)
add_ox_quiz(1, "The REAL reason an ostrich sticks its head in the sand is to search for water.", true)
add_ox_quiz(1, "The capitol city of Peru is Lima.", true)
add_ox_quiz(1, "40,000 Americans are injured by blinds each year.", false)
add_ox_quiz(1, "Alfred Hitchcock did not have a bellybutton.", true)
add_ox_quiz(1, "Cucumber, not caffeine, are more efficient at waking you up in the morning.", false)
add_ox_quiz(1, "Trees give off carbon tetraiodide, which pollutes the air.", false)
add_ox_quiz(1, "Root is needed to make most seeds form.", false)
add_ox_quiz(1, "Jewelweed is a good antidote for poison ivy.", true)
add_ox_quiz(1, "The lobster is a pest.", true)
add_ox_quiz(1, "Earthworms have six hearts.", false)
add_ox_quiz(1, "The firefly flashes is used to get a couple.", true)
add_ox_quiz(1, "Mammals are arthropods.", false)
add_ox_quiz(1, "People who study insects are called entomologist.", true)
add_ox_quiz(1, "Halle Berry received an Oscar.", true)
add_ox_quiz(1, "The last Russian Tzar was Ivan the Terrible.", false)
add_ox_quiz(1, "The first Christmas tree was made in Germany.", true)
add_ox_quiz(1, "Slovenia is a member of the European Union.", true)
add_ox_quiz(1, "The Red Bull drink was created in Germany.", false)
add_ox_quiz(1, "The Queen holds UK Passport No.1?", false)
add_ox_quiz(1, "Humphrey Bogart never said 'Play it again Sam' in Casablanca.", true)
add_ox_quiz(1, "A granny, a sheepshank and a bowline are all parts of chimney.", false)
add_ox_quiz(1, "You can still be executed for certain crimes in England?", false)
add_ox_quiz(1, "Photosynthesis takes place in the leaves of plants.", true)
add_ox_quiz(1, "Las Vegas is called 'the Big Easy'.", false)
add_ox_quiz(1, "A viper can be a car or a snake.", true)
add_ox_quiz(1, "A diode is an electrical component?", true)
add_ox_quiz(1, "A diode is an electrical tool?", false)
add_ox_quiz(1, "The city Alexandria was named after Alexander the Great?", true)
add_ox_quiz(1, "Tzar Nicholas 2 was executed in 1917?", false)
add_ox_quiz(1, "FBI means Federal Bureau of Interrogation?", true)
add_ox_quiz(1, "The last dynasty in China was the Chou?", false)
add_ox_quiz(1, "An elephant can smell water up to 3 miles away.", true)
add_ox_quiz(1, "The prefix 'giga' means a million", false)
add_ox_quiz(1, "Celery has so many calories that eating it isn't even a workout.", false)
add_ox_quiz(1, "Bruce Lee was so slow while going through his moves that they had to speed up one of his movies to make it look real.", false)
add_ox_quiz(1, "Perry White was the editor at the Daily Planet.", true)
add_ox_quiz(1, "Zip stands for Zoning Improvement Plan.", true)
add_ox_quiz(1, "A standard guitar has 5 strings.", false)
add_ox_quiz(1, "Guatemala is located in South Africa.", false)
add_ox_quiz(1, "Iceland became independent of Norway in 1944.", false)
add_ox_quiz(1, "Brasilia was declared the capital of Brazil in 1960.", true)
add_ox_quiz(1, "The Marlboro Man died of lung cancer.", true)
add_ox_quiz(1, "A single light bulb has been burning since 1901.", true)
add_ox_quiz(1, "There are more left-handed women than men.", false)
add_ox_quiz(1, "The largest man-made object is the Great Wall of China.", false)
add_ox_quiz(1, "If you mix Jack Daniels and Jim Beam together you are making a gin and tonic.", false)
add_ox_quiz(1, "When not using his chariot for travel, King Tutankhamen used camels.", false)
add_ox_quiz(1, "The longest name in the Bible is Mahershalalhashbaz.", true)
add_ox_quiz(1, "In the movie 'Fantasia' the sorcerer's name was Yensid.", true)
add_ox_quiz(1, "The fear of extreme cold, ice or frost is called crystallophobia.", false)
add_ox_quiz(1, "Billy the Kid's real name was William H. Bonney.", true)
add_ox_quiz(1, "Over 1,000 Americans died at the Alamo.", false)
add_ox_quiz(1, "Socrates taught Plato.", true)
add_ox_quiz(1, "Plato taught Aristotle.", true)
add_ox_quiz(1, "James Dean was the first actor to receive a Best Actor nomination posthumously.", true)
add_ox_quiz(1, "John Travolta's mother was in 'Saturday Night Fever'?", true)
add_ox_quiz(1, "The Hundred Years' War lasted 100 years.", false)
add_ox_quiz(1, "Proxima Centauri is the closest star to Earth.", false)
add_ox_quiz(1, "Musician Sting's real name is Reginald Dwight.", false)
add_ox_quiz(1, "Musician Sting's real name is Gordon Sumner.", true)
add_ox_quiz(1, "Romanian is a Slavic language.", false)
add_ox_quiz(1, "The Spain football team won the Euro Cup in 2008 for second time.", true)
add_ox_quiz(1, "Al Capone was the most famous gangster of New York.", false)
add_ox_quiz(1, "The country of Latvia is independent since 1995.", false)
add_ox_quiz(1, "Afrikaans is a language based in German.", false)
add_ox_quiz(1, "In the North Pole, nights last for 3 months.", false)
add_ox_quiz(1, "The maximum value of strength against Suras is 20%", true)
add_ox_quiz(1, "The FuriaRoja guild has Weapon Blacksmith.", true)
add_ox_quiz(1, "Potatoes were introduced in Europe by the Spaniards in the 16th century.", true)
add_ox_quiz(1, "Footballer Leo Messi was raised in Argentina.", false)
add_ox_quiz(1, "Jurong island was built from several smaller islands in Singapore.", true)
add_ox_quiz(1, "The 1988 Olympics were held in Barcelona.", false)
add_ox_quiz(1, "Hungarian football legend Ferenc Puskas played for the Norwegian national team.", false)
add_ox_quiz(1, "Scientology is the discipline that studies science.", false)
add_ox_quiz(1, "Don Quixote was written by Miguel de Cervantes between 1605 and 1615.", true)
add_ox_quiz(1, "Boca Juniors is traditionally considered the team of the working class in Argentina.", true)
add_ox_quiz(1, "Despite its name, Greenland doesn't have any forests.", true)
add_ox_quiz(1, "`Loch` is Scottish for Lake.", true) 
add_ox_quiz(1, "Chocolate can be dangerous for dogs.", true)
add_ox_quiz(1, "The Tintín comics were created by Belgian Georges Rainii 'Hergé'.", false)
add_ox_quiz(1, "During the winter, ice skate can be practiced in the frozen channels of Venezia.", false)
add_ox_quiz(1, "Hae Tae can drop Blessing Scroll.", true)
add_ox_quiz(1, "Glentoran plays in the Republic of Ireland league.", false)
add_ox_quiz(1, "Champagne receives its name from its inventor Monsieur Champagne.", false)
add_ox_quiz(1, "`the dog of the Baskerville` was written by Edgar Allan Poe.", false)
add_ox_quiz(1, "Arnold Schwarzenegger was born in Germany.", false)
add_ox_quiz(1, "With G8 Leadership you can increase the SP of one party member.", true)
add_ox_quiz(1, "Pink Liquid gives Chance for Pierce Attack.", true)
add_ox_quiz(1, "White Liquid gives Attack Power.", false)
add_ox_quiz(1, "Pierce doesn’t work with skills, only normal attacks.", false)
add_ox_quiz(1, "Puerto Rico is a state from the USA.", false)
add_ox_quiz(1, "2 yeti fur + and blue pearl are needed to upgrade battle sword to +8", true)
add_ox_quiz(1, "2 red pigtail ribbon is needed to upgrade silver bell to +8", true) 
add_ox_quiz(1, "2 curse book and clam are needed to upgrade jade bell to +9", true)
add_ox_quiz(1, "2 scorpion tail + and clam are needed to upgrade jade bell to +8", true)
add_ox_quiz(1, "2 leaf and blue pearl are needed to upgrade golden bug bell to +7", false)
add_ox_quiz(1, "Curse book + is needed to upgrade Bamboo bell to +5", false)
add_ox_quiz(1, "Curse book + is needed to upgrade Bamboo bell to +6", true)
add_ox_quiz(1, "Tiger hide is needed to upgrade Iron fan to +7", true)
add_ox_quiz(1, "2 tiger hide are needed to upgrade iron fan to +8", false)
add_ox_quiz(1, "2 worm out black uniform are needed to upgrade iron fan to +9", false)
add_ox_quiz(1, "A necklace for lvl 42+7 gives 3 Strength ", true)
add_ox_quiz(1, "A Helm for lvl 41+9 gives 79 of AC", true)
add_ox_quiz(1, "A Helm for lvl 41+9 gives 78 of AC", false)
add_ox_quiz(1, "Leather boots +9 gives 3 of AC.", true)
add_ox_quiz(1, "Leather boots +9 gives 5 of AC", false)
add_ox_quiz(1, "200 Red Potion (L) costs 32.000 of gold", true)
add_ox_quiz(1, "200 Red potion (L) costs 33.000 of gold", false)
add_ox_quiz(1, "Blue dress +5 gives 42 of AC", true)
add_ox_quiz(1, "Black Tunic +2 gives 102 of AC", true)
add_ox_quiz(1, "Black Tunic +2 gives 94 of AC", false)
add_ox_quiz(1, "Ebony earrings +6 gives +250 HP", false)
add_ox_quiz(1, "Ecstatic fan +7 gives 17% of Spell Speed", true)
add_ox_quiz(1, "Ecstatic fan +7 gives 15% of Spell Speed", false)
add_ox_quiz(1, "Tiger Woods is the highest paid sportsman in the world.", true)
add_ox_quiz(1, "Cung Mok is level 9.", true)
add_ox_quiz(1, "Cunk Mok is level 14.", false)
add_ox_quiz(1, "Joan is located in Asmodia.", true)
add_ox_quiz(1, "With King powers you can summon a Proud Demon King.", false)
add_ox_quiz(1, "Coins' face value is the same as the value of the metal they contain.", false)
add_ox_quiz(1, "The king of Norway is King Harald VII.", false)
add_ox_quiz(1, "The capitol city of Pakistan is Islamabad.", true)
add_ox_quiz(1, "Bulgaria is a member of the European Union.", true)
add_ox_quiz(1, "Norway is a member of the European Union.", false)
add_ox_quiz(1, "Mu-Rang is level 14.", false)
add_ox_quiz(1, "Mu-Rang is level 16.", true)
add_ox_quiz(1, "Bruges is a French city.", false)
add_ox_quiz(1, "Cerberus, the legendary creature, was a dragon with nine tails.", false)
add_ox_quiz(1, "Dante, the poet, was contemporary of Giotto.", true)
add_ox_quiz(1, "The term RADAR was coined in 1941 as an acronym for Radio Detection and Ranging.", true)
add_ox_quiz(1, "The term RADAR was coined in 1941 as an acronym for Radio Deletion and Ranging.", false)
add_ox_quiz(1, "Ludwig van Beethoven, was a German composer and pianist died on 26 March 1828", false)
add_ox_quiz(1, "In the Lord of The Rings, Gimli is one of the hobbits.", false)
add_ox_quiz(1, "In the lord of the rings, the fellowship of the ring, Gandalf is called `Gandalf the grey`", true)
add_ox_quiz(1, "The Godfather was written by Francis Ford Coppola", false)
add_ox_quiz(1, "The Aeneid is a Latin epic poem written by Virgil", true)
add_ox_quiz(1, "Stephen William Hawking is an English theoretical physicist and cosmologist.", true)
add_ox_quiz(1, "Evanescence is an American rock band founded in Little Rock, Arkansas.", true)
add_ox_quiz(1, "You need Snake Tail+ to upgrade a level 47 armor to +5", false)
add_ox_quiz(1, "A Helm for level 21 +5 gives 33 of AP.", false)
add_ox_quiz(1, "Pearl Jam is a rock band from United States.", true)
add_ox_quiz(1, "The port of Baku is situated in Azerbaijan.", true)
add_ox_quiz(1, "The first boxer to win 3 gold medals in the Olympics was László Papp.", true)
add_ox_quiz(1, "Sylvester Stallone was born in Nueva York.", true)
add_ox_quiz(1, "Ray Kroc is the founder of McDonalds as we know it today.", true)
add_ox_quiz(1, "The capital of Seychelles is Victoria.", true)
add_ox_quiz(1, "The capital of Seychelles is Freetown.", false)
add_ox_quiz(1, "The capital of Canada is Ottawa.", true)
add_ox_quiz(1, "The capital of Paraguay is Asuncion.", true)
add_ox_quiz(1, "The capital of Jamaica is Kingston.", true)
add_ox_quiz(1, "The capital of Vietnam is Hanoi", true)
add_ox_quiz(1, "The capital of Romania is Bucarest.", true)
add_ox_quiz(1, "The capital of Australia is Sydney.", false)
add_ox_quiz(1, "The capital of New Zealand is Auckland.", false)
add_ox_quiz(1, "The North Pole is the least populated country in the world.", false)
add_ox_quiz(1, "The world's oldest song was created in Syria, in the city of Ugarit.", true)
add_ox_quiz(1, "The largest known dinosaur is the Brachiosaurus.", false)
add_ox_quiz(1, "The most ferocious dinosaur known after the T-Rex was the Deinonychus.", true)
add_ox_quiz(1, "The term RAM means Range Access Memory.", false)
add_ox_quiz(1, "The term ENOC is an acronym for Emirates National Oil Company.", true)
add_ox_quiz(1, "The term ENOC is an acronym for Emirates National Oil Complaint.", false)
add_ox_quiz(1, "The term SQL is an acronym for Structured Question Language.", false)
add_ox_quiz(1, "The term CD-ROM is an acronym for Compact Disc redirect-only memory.", false)
add_ox_quiz(1, "The term BBC is an acronym for Britain Broadcasting Corporation.", false)
add_ox_quiz(1, "The butterfly has a sucker mouth.", false)
add_ox_quiz(1, "Titanic is cited as the most expensive film of all time.", false)
add_ox_quiz(1, "The most expensive bikini in the world costs 30 million dollars.", true)
add_ox_quiz(1, "On the fiftieth birthday of the Sultan of Brunei starred Michael Jackson.", true)
add_ox_quiz(1, "The world's most expensive game is Shenmue.", true)
add_ox_quiz(1, "The world's most expensive game is Final Fantasy VII.", false)
add_ox_quiz(1, "The most expensive hotel ever built is the Emirates Palace in Abu Dhabi", true)
add_ox_quiz(1, "The real name of Nostradamus was Michel Notre Dame", true)
add_ox_quiz(1, "The real name of Nostradamus was Michael Nostradamus", false)
add_ox_quiz(1, "Michel Notre Dame (Nostradamus) was a doctor", true)
add_ox_quiz(1, "Nostradamus wife and sons died because of the bubonic pest.", true)
add_ox_quiz(1, "Hagakure is a book inspirited in the code of Bushido.", true)
add_ox_quiz(1, "Confucius wrote 4 books called the four classic books.", true)
add_ox_quiz(1, "The 1st classic book of Confucius is called Ta-Hio (Great Science)", true)
add_ox_quiz(1, "The 1st classic book of Confucius is called Ta-Hiokinai (Great Science)", false)
add_ox_quiz(1, "The 1st book of Confucius is dedicated to the knowledge of sound science", false)
add_ox_quiz(1, "The 2nd classic book of Confucius is called Chung-Yung", true)
add_ox_quiz(1, "The 2nd classic book of Confucius is called Chung-Pumping", false)
add_ox_quiz(1, "The 2nd classic book of Confucius talks about the good kings and government justice", true)
add_ox_quiz(1, "The 2nd classic book of Confucius talks about the good boy killing ducks in the garden", false)
add_ox_quiz(1, "The 3rd classic book of Confucius is called Lung-Yu", true)
add_ox_quiz(1, "The 3rd classic book of Confucius is called Lungestic-Yumanji", false)
add_ox_quiz(1, "The 3rd classic book of Confucius talks about money payments for computer science", false)
add_ox_quiz(1, "Analectas is the 3rd classic book of Confucius", true)
add_ox_quiz(1, "The 4th classic book of Confucius is called Meng-Tse", true)
add_ox_quiz(1, "The 4th classic book of Confucius is called Mengine-Tuskemeahoro", false)
add_ox_quiz(1, "Sun Tzu wrote the book `The art of War`", true)
add_ox_quiz(1, "Sun Bin Wrote the book `The art of War II`", true)
add_ox_quiz(1, "Sun Bin wrote the book `The art of war`", false)
add_ox_quiz(1, "Sun Tzu wrote the book `The art of war II`", false)
add_ox_quiz(1, "Sun Bin is a descendant of Sun Tzu and wrote `The art of war II`", true)
add_ox_quiz(1, "Sun Tzu is a descendant of Sun Bin and wrote `The art of war`", false)
add_ox_quiz(1, "Sun Bin is a descendant of Sun Tzu and wrote `The art of war`", false)
add_ox_quiz(1, "Sun Tzu was a Chinese general that wrote `The art of war`", true)
add_ox_quiz(1, "Napoleon, Maquiavelo and Mao Tse Tung was inspired by the book `The art of war`", true)
add_ox_quiz(1, "The Amazonas is a river of South America.", true)
add_ox_quiz(1, "The Amazonas is a river of South Africa.", false)
add_ox_quiz(1, "Garra rufa fish are extremely vicious and can strip flesh from the bone in a matter of minutes.", false)
add_ox_quiz(1, "The Austrian town of Salzburg literally means 'Mountain Dance'.", false)
add_ox_quiz(1, "There are only four American states that contain the letter 'Y' in their state name.", false)
add_ox_quiz(1, "Chrysotile, ammonite and crocidolite are all varieties of semi-precious stones.", false)
add_ox_quiz(1, "Phil 'The Power' Taylor was the first darts player to make more than £1,000,000 in prize money at darts.", true)
add_ox_quiz(1, "Drinking water in large quantities slimming", false)
add_ox_quiz(1, "I can eat as much 'Light' food as I want, because I do not get fat", false)
add_ox_quiz(1, "Olive oil is healthier than butter", true)
add_ox_quiz(1, "It is best not to eat vegetables because very fat.", false)
add_ox_quiz(1, "It is not good to cook with wine.", false)
add_ox_quiz(1, "Carrots are good for the eyes.", true)
add_ox_quiz(1, "Lentils are a food rich in iron.", true)
add_ox_quiz(1, "Most cases of obesity are due to genetic causes.", false)
add_ox_quiz(1, "The eggs are not good for the liver.", false)
add_ox_quiz(1, "Soy is an excellent source of protein, comparable to eat a good steak.", true)
add_ox_quiz(1, "I can eat fruit all the time because it is not fattening.", false)
add_ox_quiz(1, "The raw egg feeds more than if egg is cooked.", false)
add_ox_quiz(1, "The psychologist and educator F. Stanley Hall invented the term `teenager`.", true)
add_ox_quiz(1, "The psychologist and educator F. Stanley Hallegance invented the term `teenager`.", false)
add_ox_quiz(1, "Milli Vanilli duo composed of Fabrice 'Fab' Morvan and Rob Pilatus was formed in Germany in the mid 80's.", true)
add_ox_quiz(1, "Milli Vanilli duo composed of Fabrice 'Fab' Morvan and Rob Pilatus was formed in Germany in the mid 70's.", false)
add_ox_quiz(1, "The group Milli Vanilli was a fraud and used playback at concerts.", true)
add_ox_quiz(1, "The group Milli Vanilli, the Grammy was withdrawn because they were a fraud.", true)
add_ox_quiz(1, "Egyptian makeup was used to cure or prevent disease.", true)
add_ox_quiz(1, "'New Coke' was considered the worst mistake in marketing history.", true)
add_ox_quiz(1, "The tomato was known as the apple of love.", true)
add_ox_quiz(1, "The world's oldest instrument is a flute made 35,000 years ago.", true)
add_ox_quiz(1, "The world's oldest instrument is a violin made 35,000 years ago.", false)
add_ox_quiz(1, "A bone flute is the world's oldest instrument.", true)
add_ox_quiz(1, "A wooden flute is the world's oldest instrument.", false)
add_ox_quiz(1, "The Gangkhar Puensum, is the largest mountain in the world that no one has climbed to the top.", true)
add_ox_quiz(1, "All the world's mountains have been climbed to the top once.", false)
add_ox_quiz(1, "It's a myth that people have sent mail itself.", false)
add_ox_quiz(1, "In classical times always wrote in capital letters.", true)
add_ox_quiz(1, "The first Sudoku was created by architect Howard Garns.", true)
add_ox_quiz(1, "The first Sudoku was created by architect Wayne Gould.", false)
add_ox_quiz(1, "The wife of a real estate developer of a real estate company, was the person who had the idea of the Hollywood sign.", true)
add_ox_quiz(1, "Universal Pictures was the creator of the Hollywood sign.", false)
add_ox_quiz(1, "20th Century Fox was the creator of the Hollywood sign.", false)
add_ox_quiz(1, "Warner Bros was the creator of the Hollywood sign.", false)
add_ox_quiz(1, "Metro-Goldwyn-Mayer was the creator of the Hollywood sign.", false)
add_ox_quiz(1, "Columbia Pictures was the creator of the Hollywood sign.", false)
add_ox_quiz(1, "Paramount Pictures was the creator of the Hollywood sign.", false)
add_ox_quiz(1, "The youngest mother in history was 5 years old", true)
add_ox_quiz(1, "The tallest man in the world came to measuring 2.72 meters and weighing 223 kilos.", true)
add_ox_quiz(1, "The tallest man in the world never stopped growing until his death at age 22.", true)
add_ox_quiz(1, "The Guinness book of records was created by the manager of the Guinness microbrewery.", true)
add_ox_quiz(1, "A village in the Chilean Andes have blue skin.", true)
add_ox_quiz(1, "A village in the Chilean Andes is the only town with humans with blue skin.", false)
add_ox_quiz(1, "The library of Alexandria was the first library in history.", false)
add_ox_quiz(1, "The library of Ashurbanipal was the first library in history.", true)
add_ox_quiz(1, "The horse is an invertebrate animal.", false)
add_ox_quiz(1, "Living things do three things: relationships, nutrition and reproduction.", true)
add_ox_quiz(1, "Lizards are reptiles.", true)
add_ox_quiz(1, "The starfish is an echinoderm.", true)
add_ox_quiz(1, "Ocean trenches are very great depths in the oceans.", true)
add_ox_quiz(1, "Plant cells do photosynthesis.", true)
add_ox_quiz(1, "Insects have four pairs of legs.", false)
add_ox_quiz(1, "The core of the earth is on the mantle.", false)
add_ox_quiz(1, "A nebula is a cloud of planets.", false)
add_ox_quiz(1, "A prokaryotic and eukaryotic cells are not different at all.", false)
add_ox_quiz(1, "The snail is a gastropod.", false)
add_ox_quiz(1, "Some amphibians have metamorphosis.", true)
add_ox_quiz(1, "At the nodes of the stem leaving the leaves and branches.", true)
add_ox_quiz(1, "Saturn is an asteroid.", false)
add_ox_quiz(1, "Jupiter is not the largest planet in the solar system.", false)
add_ox_quiz(1, "Water is the most abundant substance in all organisms.", true)
add_ox_quiz(1, "The lithosphere is the layer of rock that form Earth.", true)
add_ox_quiz(1, "The cephalopods such as octopus have antennas.", false)
add_ox_quiz(1, "The triton is an amphibian.", true)
add_ox_quiz(1, "Horses have an autotrophic feeding.", true)
add_ox_quiz(1, "The gills of fish are protected by the operculum.", true)
add_ox_quiz(1, "Our galaxy is the Milky Way.", true)
add_ox_quiz(1, "The crocodile is viviparous.", false)
add_ox_quiz(1, "The crocodile is oviparous.", true)
add_ox_quiz(1, "The jellyfish has teeth that changes every year.", false)
add_ox_quiz(1, "Animal cells have chloroplasts.", false)
add_ox_quiz(1, "The ridge is a high mountain range.", true)
add_ox_quiz(1, "The human body has no sweat glands.", false)
add_ox_quiz(1, "Venus is a planet interior.", true)
add_ox_quiz(1, "Polaris marks the north direction.", true)
add_ox_quiz(1, "The stars that emit light itself are the stars.", true)
add_ox_quiz(1, "Lizards are amphibians.", false)
add_ox_quiz(1, "The spider and the scorpion are arachnids.", true)
add_ox_quiz(1, "The moon orbits around Mars.", false)
add_ox_quiz(1, "Birds breathe through lungs.", true)
add_ox_quiz(1, "The closest planet to the sun is Venus.", false)
add_ox_quiz(1, "The ant has a sucker mouth.", false)
add_ox_quiz(1, "The oceans are formed by salt water.", true)
add_ox_quiz(1, "The rotary motion of a planet is turning on itself.", true)
add_ox_quiz(1, "Translational motion of a planet is turning on itself.", false)
add_ox_quiz(1, "The earth is an outer planet.", false)
add_ox_quiz(1, "The caudal fin of the fish is in the abdomen.", false)
add_ox_quiz(1, "Telugu is a language spoken in the Southeast of India", true)
add_ox_quiz(1, "Telgu is a language spoken in the Southeast of Japan", false)
add_ox_quiz(1, "Tetulu is the official language of Angola.", false)
add_ox_quiz(1, "If you want to learn Telugu you must go to the Southeast of India", true)
add_ox_quiz(1, "Tellurium is used as a color of porcelain and video.", true)
add_ox_quiz(1, "Felipe IV accused the Order of the Templars of paganism and sodomy.", true)
add_ox_quiz(1, "Felipe IV accused the Order of the Templars of unshakable faith.", false)
add_ox_quiz(1, "The order of the templars was founded by Hugues Des Payns.", true)
add_ox_quiz(1, "The order of the Templars was created to protect pilgrims in the Holy Land.", true)
add_ox_quiz(1, "The order of the Templars was created to protect pilgrims in the Unholy Land.", false)
add_ox_quiz(1, "The order of the Templars was created to protect poor man around the world.", false)
add_ox_quiz(1, "After the suppression of the Order of the Templars Philip IV took over much of their wealth.", true)
add_ox_quiz(1, "Philip IV becomes leader of the Templar order to crush the poor.", false)
add_ox_quiz(1, "Philip IV donated large quantities of gold to the Knights Templar because he loved the leader.", false)
add_ox_quiz(1, "The Ember is a time of fasting is done in the beginning of each of the four seasons.", true)
add_ox_quiz(1, "Teide is a volcano located on an island.", true)
add_ox_quiz(1, "Teide is a volcano located on a raft.", false)
add_ox_quiz(1, "Teide is a volcano located in a mountain chain of Alaska.", false)
add_ox_quiz(1, "Teide is a popular Mediterranean food.", false)
add_ox_quiz(1, "Tenochtitlan was the capital of the Aztec empire.", true)
add_ox_quiz(1, "Tenochtitlan was the capital of the empire of the Mayas.", false)
add_ox_quiz(1, "Tenochtitlan was the capital of the Inca empire.", false)
add_ox_quiz(1, "A tenor is the most acute of male voices.", true)
add_ox_quiz(1, "A tenor is the most serious of male voices.", false)
add_ox_quiz(1, "A tenor is the most strident male voices.", false)
add_ox_quiz(1, "The tenora is a wind instrument like the oboe.", true)
add_ox_quiz(1, "The tenora is a wind instrument like the xylophone.", false)
add_ox_quiz(1, "The tenora is a wind instrument like the violin.", false)
add_ox_quiz(1, "The tenora is a wind instrument like the saxophone.", false)
add_ox_quiz(1, "Juan Tenorio is the main character in the play The Trickster of Seville.", true)
add_ox_quiz(1, "Juan Tenorio is the main character in the novel The Trickster of Murcia.", false)
add_ox_quiz(1, "Juan Tenorio is the main character in the novel The Trickster of the Sardine.", false)
add_ox_quiz(1, "The Trickster of Seville was written by Tirso de Molina.", true)
add_ox_quiz(1, "The Trickster of Seville was written by Juan Tenorio.", false)
add_ox_quiz(1, "The theodolite is an instrument of measurement used in surveying.", true)
add_ox_quiz(1, "The theodolite is an instrument of measurement used in Geodesy", true)
add_ox_quiz(1, "The theodolite is an instrument of measurement used in astronomy.", true)
add_ox_quiz(1, "The theodolite is an instrument of measurement used in diving.", false)
add_ox_quiz(1, "Theology is a science that deals with God and his attributes and perfections.", true)
add_ox_quiz(1, "Theology is a science that deals with God and his defects and refunds.", false)
add_ox_quiz(1, "A theorem expresses a scientifically provable assertion.", true)
