#pragma once

enum 
{
	PARTY_CAN_JOIN_MAX_LEVEL	= 30,
	DEFAULT_ATTACK_SPEED		= 100,
	DEFAULT_MOVE_SPEED			= 200,
	MOVEMENT_SPEED_LIMIT		= 250,
	MAX_MEMBER_INTRO_PARTY		= 8,
	MAX_ITEM_STACK				= 5000,
};

//#define _IMPROVED_PACKET_ENCRYPTION_
//#define ENABLE_MIRRORING_PROTO
//#define ENABLE_SEQUENCE_SYSTEM
#define ENABLE_UDP_BLOCK
#define CLIENT_VERSION "20181010"
#define LSS_SECURITY_KEY "1234abcd5678efgh"
#define VERSION "1337"

#define ENABLE_WOLFMAN
#define ENABLE_TARGET_INFO
#define ENABLE_ELEMENT_TARGET
#define ENABLE_MASTER_SKILLBOOK_NO_STEPS
#define ITEM_CHECKINOUT_UPDATE
//#define ENABLE_OPEN_MULTIPLE
#define ENABLE_INSTANT_5_BONUS
#define ENABLE_XOSHIRO